name: Tests

on:
  push:
    branches: [canary]
  pull_request:
    branches: [canary]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.35

      - name: Install dependencies
        run: bun install

  bun-tests:
    needs: setup
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.34

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Build project
        run: |
          bun run build
          bun run create-brisa:build

      - name: Run Bun tests
        run: bun run test

  e2e-tests:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.34

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Build project
        run: bunx playwright install
      - run: bunx playwright install-deps
      - run: bun run build

      - name: Run e2e tests
        run: bun run test:e2e

  node-tests:
    needs: setup
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.34

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Build project
        run: |
          bun run build
          bun run create-brisa:build

      - name: Run Node.js tests
        run: bun run test:node
